### PR TITLE
Remove expect in data conversion.

### PR DESCRIPTION
**Pull request by musitdev**
# Summary
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.

From issue #511
# Changelog
 * Change `From<Vec<u8>>` to `TryFrom<Vec<u8>>`. Update trait bound.
 * Trace error on channel send error instead of expect().

# Testing

# Outstanding issues

### CODE REVIEW

**Comment by 0xmovses** [comment]
`cargo test --test eth_movement -- --nocapture --test-threads=1`

```
failures:
    test_movement_client_should_successfully_call_lock_and_abort
    test_movement_client_should_successfully_call_lock_and_complete

test result: FAILED. 8 passed; 2 failed; 2 ignored; 0 measured; 0 filtered out; finished in 132.92s

```

**Comment by musitdev** [comment]
Do you have the same error as me: Error: `FaucetClientError { inner: Inner { kind: HttpStatus(500), source: None } }` ?
I don't understand why the faucet fail.
I rebuild movement cli from the current main.

**Comment by musitdev** [comment]
I think it comes from the fact that the movement process is not killed correctly or take time to kill.

**Comment by musitdev** [comment]
It's a timing issue, on my PC the node take time to start. It has a big local db so it take several seconds to start and when the faucet fund request is sent the node is not completely started. The faucet take some more time to be ready.

**Comment by musitdev** [comment]
I get the error: `Transaction submission error: Unknown error Transaction committed on chain, but failed execution: NUMBER_OF_ARGUMENTS_MISMATCH` 
related to the other PR.

**Comment by 0xmovses** [comment]
Yes this error is expected now, and I'm working on a fix on this branch https://github.com/movementlabsxyz/movement/pull/614

**Comment by mzabaluev** [comment]
This needs updating from main.

> Yes this error is expected now, and I'm working on a fix on this branch #614

@0xmovses That PR got closed without merging, is there another fix?

**Pull request closed without merging**
