### PR TITLE
Remove unused shared unify bridge crates update bridge tests/

### PR DESCRIPTION
**Pull request by 0xmovses**
# Summary
Reorgs the bridge repo to remove redundant code. Notable everything in `shared/`. Adds in initial structure for event state machine by @musitdev 

# Changelog
- Refactor integration tests into `/tests/` and fix logical errors
- Remove redundant code
- Remove old CI job for `/shared` tests
- Reorg crates

# Testing
1. `cargo test --test client_eth_movement -- --nocapture --test-threads=1 `
2. `cargo test --test client_movement_eth -- --nocapture --test-threads=1 `

# Outstanding issues
Some unused fields in structs for the event state machine because the rest of the implementation is in: 
https://github.com/movementlabsxyz/movement/pull/624
I added the `#[allow(dead_code)]` decorator for these structs

### CODE REVIEW

**Comment by andygolay** [comment]
Here's what's left to clean up:

- In `harness.rs`:

  - `set_initiator_contract`, `set_signer_address` and `set_weth_contract` don't appear to exist
  
- In `movement.rs` 

  - getting a lot of ``self` parameter is only allowed in associated functions
associated functions are those in `impl` or `trait` definition`  . Also getting this in `setup.rs`
  - Should `Address` be `BridgeAddress`?
  
- In `utils.rs`, `initiator_set_timelock` doesn't appear to exist

- Throughout, we should check our time locks, to make sure they're correct. I added default timelocks to make things pass so anywhere there's `args.time_lock` should be reviewed.

**Comment by andygolay** [comment]
> Here's what's left to clean up to make tests run:
> 
> * In `harness.rs`:
>   
>   * `set_initiator_contract`, `set_signer_address` and `set_weth_contract` don't appear to exist
> * In `movement.rs`
>   
>   * getting a lot of ``self`parameter is only allowed in associated functions associated functions are those in`impl` or `trait` definition`  . Also getting this in `setup.rs`
>   * Should `Address` be `BridgeAddress`?
> * In `utils.rs`, `initiator_set_timelock` doesn't appear to exist
> * Throughout, we should check our time locks, to make sure they're correct. I added default timelocks to make things pass so anywhere there's `args.time_lock` should be reviewed.

**Comment by andygolay** [comment]
Update on progress:

got all tests passing except `test_eth_client_should_deploy_initiator_contract`. Seems to be related to how `Config::build_for_test` is working

On main there's Option for the three addresses:

```
pub struct Config {
	pub rpc_url: Url,
	pub ws_url: Url,
	#[serde_as(as = "serde_with::DisplayFromStr")]
	pub signer_private_key: PrivateKeySigner,
	pub initiator_contract: Option<Address>,
	pub counterparty_contract: Option<Address>,
	pub weth_contract: Option<Address>,
	pub gas_limit: u64,
}

impl Config {
	pub fn build_for_test() -> Self {
		Config {
			rpc_url: "http://localhost:8545/".parse().unwrap(),
			ws_url: "ws://localhost:8545/".parse().unwrap(),
			signer_private_key: PrivateKeySigner::random(),
			initiator_contract: None,
			counterparty_contract: None,
			weth_contract: None,
			gas_limit: 10_000_000_000,
		}
	}
}
```

But in this PR's branch, they're strings:

```
pub struct Config {
	pub rpc_url: Url,
	pub ws_url: Url,
	#[serde_as(as = "serde_with::DisplayFromStr")]
	pub signer_private_key: PrivateKeySigner,
	pub initiator_contract: String,
	pub counterparty_contract: String,
	pub weth_contract: String,
	pub gas_limit: u64,
}

impl Config {
	pub fn build_for_test() -> Self {
		Config {
			rpc_url: "http://localhost:8545/".parse().unwrap(),
			ws_url: "ws://localhost:8545/".parse().unwrap(),
			signer_private_key: PrivateKeySigner::random(),
			initiator_contract: "0x1234567890abcdef1234567890abcdef12345678".to_string(),
			counterparty_contract: "0x1234567890abcdef1234567890abcdef12345678".to_string(),
			weth_contract: "0x1234567890abcdef1234567890abcdef12345678".to_string(),
			gas_limit: 10_000_000_000,
		}
	}
}
```

Thinking maybe the `String` part is fundamentally incorrect, and they should be `Option<Address>` instead?
I added dummy values, the `0x123...` address
but not sure whether those fields should go back to being `Option<Address>` (edited) 

When I try it with `Option` and run `rust_backtrace=1 cargo test --test client_eth_movement test_eth_client_should_deploy_initiator_contract  -- --nocapture --test-threads=1` it fails with

```
thread 'test_eth_client_should_deploy_initiator_contract' panicked at protocol-units/bridge/service/tests/harness.rs:119:14:
Failed to create EthClient: Missing initiator contract address
```

**Review by andygolay — APPROVED** [review]
Client integration tests pass. 

LGTM 

```
|              __             
|           .--.;_.'-.          
|      _.,  \__.'  ;@ '.        
|    .';  `.  ;   __..-"'o      
|   ;   ;' ;   ;_/   ._.-'      
|   '. }  :   /  `. _i/v\.      
|   ;  i',;  (  \_.' .(_)       
|  ;  ' /{ \/ '.   .r_.'        
|  '\  ;  .'  .''-';_           
|   ''-. ;   /     '.`.         
|  \    ;    '.     ; '.        
|   '._.;   _ ;     ;  ;        
|        \.' '.__.-i   ;        
|         'wWw'    "wWw' 
|  
|     ____________________________
|    |                            |
|    |                            |
|    |            |\              |
|    |            | \             |
|    |            |  \            |
|    |            |   \           |
|    |            |    \          |
|    |            |     \         |
|    |            |______\        |
|    |           /        \       |
|    |__________/__________\______|
|             ~~~~~~~~~~~~~~~~~~~~~~~~~
|            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
|           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Review by musitdev — APPROVED** [review]
For the Rust code, it's ok for me. I didn't look at the smart contract code.

**Review by l-monninger — APPROVED** [review]

**Pull request merged**
