### PR TITLE
Docker Compose Rewrite

### PR DESCRIPTION
**Pull request by l-monninger**
# Summary
- **RFCs**: $\emptyset$.
- **Categories**:`protocol-units`

Extensive changes across all protocol units to accommodate `docker-compose` setups and process runtimes. 

# Changelog

- Well known configs from https://github.com/movementlabsxyz/movement/pull/93 modified to support non-native service dependencies. Generally, this means adding to the config `listen_` and `connection_` hostnames and ports. 
- General cleanup of #93.
- Rewrite of the actual `docker-compose` setup to no longer use the monolith.
- Minor modifications to build and publish flow.
- **REMOVES MONZA** as it time consuming to maintain throughout this process. 

# Testing

- Manual testing only; CI tests not yet added besides those for builds.
- To confirm behavior run `just suzuka-full-node docker-compose setup.local`

# Outstanding issues
1. `just suzuka-full-node docker-compose setup.local` shell does not exit cleanly. Leaves user unable to see additional input. 
2. Still pretty messy. Better standardization and patterns should be introduced as this continues to grow.
3. Replacement flags for debugging are pretty much useless as the setup will always be one ChainID ahead.

### CODE REVIEW

**Comment by l-monninger** [comment]
gali

**Comment by l-monninger** [comment]
gali

**Comment by l-monninger** [comment]
gali

**Comment by l-monninger** [comment]
Looking into Celestia Websocket unavailability. The only parameter related to the websocket not listening on `0.0.0.0` was `--proxy_app`. 

If `--proxy_app` does not prove to be a fix, then we will have to take a deeper dive into Celestia networking in Docker containers. Unfortunately, there are no merged docs; and, there's is not much here about specifically using `celestia-appd` within Docker:  https://github.com/celestiaorg/docs/pull/1364

A fall back could be use use a Mocha or Arabic light client. Additional setup scripts for this would need to be provided.

**Comment by l-monninger** [comment]
https://github.com/celestiaorg/celestia-app/discussions/3578

**Review by radupopa369 — APPROVED** [review]

**Comment by radupopa369** [comment]
just fix the conflicts at merge it ; it PR is too huge to review in a timely manner

**Pull request merged**
