### PR TITLE
Primata/338 only owner

### PR DESCRIPTION
**Pull request by 0xPrimata**
# Summary
- **RFCs**: https://github.com/movementlabsxyz/movement/issues/338
- **Categories**:`protocol-units`

add nonce comment, add onlyOwner, add ownership to movetoken, fix tests

# Changelog

# Testing

tests are fixed

# Outstanding issues

### CODE REVIEW

**Comment by 0xmovses** [comment]
There are changes here to MOVE.token but I think that's outside the scope of this PR. In the Issue the change should just be for Initiator and Counterparty contracts on both Eth and .move modules, maybe the Move word was confusing!

**Comment by 0xmovses** [comment]
Could you also add both a solidity unit test where a non-owner tries to call `abortBridgeTransfer`? And also the equivalent unit test on the .move Initiator module. Thanks!

**Comment by 0xPrimata** [comment]
Could you rereview @0xmovses ?

**Comment by 0xmovses** [comment]
Is this ready for review?

**Review by 0xmovses — CHANGES_REQUESTED** [review]
This looks good, but could you remove all the changes for `MCR.sol` and `MovementStaking.t.sol` I think they are just formatting changes. It will cause reviewers of the feature branch to do a double take if we leave it in.

**Comment by 0xPrimata** [comment]
all resolved

**Comment by 0xmovses** [comment]
Nice, thank you.

**Pull request merged**
