### PR TITLE
Infra Integration

### PR DESCRIPTION
**Pull request by l-monninger**
WIP

### CODE REVIEW

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by 0xmovses** [comment]
Is this re. Atlantis business?

**Comment by l-monninger** [comment]
Yeah

**Comment by l-monninger** [comment]
When this is done this will setup a PR workflow with movementlabsxyz/infra that's preps the latter for your deployment into a dynamic environment.

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra integration

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Comment by l-monninger** [comment]
infra testing

**Pull request closed without merging**
