### PR TITLE
High Sequence Number Elimination and No Redundant Sequence Number by Node

### PR DESCRIPTION
**Pull request by l-monninger**
# Summary
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.

# Changelog

# Testing

# Outstanding issues

### CODE REVIEW

**Comment by andygolay** [comment]
Could you please fill out the PR description with a little more context? I'm not very familiar with this specific issue.

I'm seeing a couple conflicting files and also unclear on why to merge into `[l-monninger/high-sequence-number-dos](https://github.com/movementlabsxyz/movement/tree/l-monninger/high-sequence-number-dos)`.

**Comment by l-monninger** [comment]
@andygolay This is PR relative to #597. Comments on this means of preventing this kid of DOS are there.

**Comment by andygolay** [comment]
> @andygolay This is PR relative to #597. Comments on this means of preventing this kid of DOS are there.

Got it. So the gc prevents redundant sequence numbers? Seems good as long as the `suzuka-full-node-malicious` check is passing.

`Checks / unit-tests` is failing with

```
test transaction_pipe::tests::test_pipe_mempool_with_duplicate_transaction has been running for over 60 seconds
```

Is that expected? It passes in #597.

**Comment by l-monninger** [comment]
> Checks / unit-tests is failing with

test transaction_pipe::tests::test_pipe_mempool_with_duplicate_transaction has been running for over 60 seconds
Is that expected? It passes in https://github.com/movementlabsxyz/movement/pull/597.

That's unexpected. I will investigate.

**Comment by l-monninger** [comment]
@andygolay unit tests should be resolved, but e2e test just flaked.

**Comment by mzabaluev** [comment]
It would be good to give a description of how these slots are going to work.
Also, since this will affect transaction submission, this should make it into a MIP documenting the behavior, but perhaps this can be done later.

**Review by andygolay — DISMISSED** [review]
:shipit:

**Pull request merged**
