### PR TITLE
Exploratory Branch for Addressing Missing Bridge Indexer Events

### PR DESCRIPTION
**Pull request by l-monninger**
# Summary
- **RFCs**: $\emptyset$.
- **Categories**: `protocol-units`

The Bridge Indexer is missing events. Logs from the Bardock node these events are being missed generally. The currently leading guess is that this is related to #856. However, this branch is open for checking several other possibilities.

# Changelog

# Testing

# Outstanding issues

### CODE REVIEW

**Comment by l-monninger** [comment]
Seems like all is well with #690 merged in. For any looking to verify, you can...
- `just bridge-solo native build.eth-holesky.mvt-bardock-testnet.indexer --keep-project`
- Bridge over with the UI: https://bridge.testnet.movementnetwork.xyz/
- Check your Hasura server at: http://localhost:8085/ (you will have to track the public tables the first time)

**Comment by l-monninger** [comment]
Unit tests failures are the same as #690

**Review by musitdev — APPROVED** [review]

**Comment by 0xmovses** [comment]
Sadly @l-monninger "The base branch requires all commits to be signed"

**Comment by l-monninger** [comment]
@0xmovses not if you are me.

**Pull request merged**
