### PR TITLE
feat: add bridge label to workflow

### PR DESCRIPTION
**Pull request by andygolay**
# Summary
Added bridge label to `solidity-bridge-tests` workflow.

# Changelog

```
  solidity-bridge-tests:
    if: contains(github.event.label.name, 'bridge') 
```

# Testing

Hope it passes CI

# Outstanding issues

### CODE REVIEW

**Comment by 0xmovses** [comment]
We would want to apply this for all the bridge integration tests and move module tests also.

**Comment by 0xmovses** [comment]
@andygolay Just noticed there is a naming convention we should stick to. Use the label name `cicd:bridge`

**Comment by andygolay** [comment]
> @andygolay Just noticed there is a naming convention we should stick to. Use the label name `cicd:bridge`

Will just close this to avoid overlapping with https://github.com/movementlabsxyz/movement/pull/549

**Comment by 0xmovses** [comment]
Let's merge this as #549 wont go in, @musitdev is going to bring back the missing method instead.

**Review by musitdev — APPROVED** [review]

**Pull request merged**
