### PR TITLE
ENG-426-Add-Grafana-logging-stack

### PR DESCRIPTION
**Pull request by radupopa369**
Updated the REDME.md to contain a step by step guide on how one would setup a linux server to configure the Grafana Observability Stack to send logs, metrics and traces to Grafana Cloud. 
This info can be shared with the community on how to setup a node in the future.

### CODE REVIEW

**Comment by radupopa369** [comment]
gali: I am testing infra for my PR`

**Comment by l-monninger** [comment]
**Gali PR:** https://github.com/movementlabsxyz/infra/pull/43

**Comment by radupopa369** [comment]
need to brach of movementlabsxyz/movement/87/l-monninger/suzuka-docker-compose-stack 
closing this PR

**Comment by radupopa369** [comment]
gali: create new infra

**Comment by l-monninger** [comment]
**Gali PR:** https://github.com/movementlabsxyz/infra/pull/43

**Comment by radupopa369** [comment]
gali create new infra please

**Comment by l-monninger** [comment]
**Gali PR:** https://github.com/movementlabsxyz/infra/pull/46

**Comment by radupopa369** [comment]
gali create new infra with this image 2f75b348936c0538a8d0aa766ea475235a32a931

**Pull request closed without merging**
