### PR TITLE
Bridge GraphQL Normalization

### PR DESCRIPTION
**Pull request by l-monninger**
# Summary
- **RFCs**: $\emptyset$.
- **Categories**: `protocol-units`

# Changelog

# Testing

# Outstanding issues

### CODE REVIEW

**Comment by andygolay** [comment]
This seems good in regards to the code normalization.

I still get the "Failed to create indexer DB client" error I mention in #843 with this branch.
image

So far the only PR I've tested against locally where I don't get the error, is #824 

Maybe it would be good to merge #824 into main first, then rebase this against main?

**Comment by l-monninger** [comment]
Yes, this needs https://github.com/movementlabsxyz/movement/pull/821 to run without the indexer. I will merge it in.

**Comment by andygolay** [comment]
> Yes, this needs #821 to run without the indexer. I will merge it in.

LGTM, my approval wouldn't matter as I'm not a global codeowner but after resolving conflicts seems good to merge.

**Comment by andygolay** [comment]
@l-monninger it seems like there's a new error on `main` after merging this:
image

```
2024-11-15T14:43:46.228717Z ERROR bridge_service: Chain two event stream return an error: Error during onchain call: MWT get_account_events status error 404 Not Found
```

From

```
async fn get_account_events(
	rest_url: &str,
	account_address: &str,
	event_type: &str,
	field_name: &str,
	start_version: u64,
	timeout_sec: u64,
) -> Result<Vec<VersionedEvent>, BridgeContractError> {
	let url = format!(
		"{}/v1/accounts/{}/events/{}/{}",
		rest_url, account_address, event_type, field_name
	);

	let client = reqwest::Client::new();

	// Send the GET request
	let response = match tokio::time::timeout(
		tokio::time::Duration::from_secs(timeout_sec),
		client
			.get(&url)
			.query(&[("start", &start_version.to_string()[..]), ("limit", "10")])
			.send(),
	)
	.await
	{
		Ok(res) => res.map_err(|e| {
			BridgeContractError::OnChainError(format!(
				"MVT get_account_events get request error:{}",
				e
			))
		})?,
		Err(err) => {
			//sleep a few second before retesting.
			tokio::time::sleep(tokio::time::Duration::from_secs(3)).await;
			Err(BridgeContractError::OnChainError(format!(
				"MVT get_account_events Rpc entry point timeout:{err}",
			)))?
		}
	};

	if response.status().is_success() {
		let body = response.text().await.map_err(|e| {
			BridgeContractError::OnChainError(format!(
				"MVT get_account_events get response content error:{e}",
			))
		})?;
		let json_result = serde_json::from_str(&body);
		match json_result {
			Ok(data) => Ok(data),
			Err(e) => Err(BridgeContractError::OnChainError(format!(
				"MVT get_account_events json convertion error:{e} with response body:{body}",
			))),
		}
	} else {
		Err(BridgeContractError::OnChainError(format!(
			"MVT get_account_events status error {}",
			response.status()
		)))
	}
}
```

in `event_monitoring.rs`

running

```
CELESTIA_LOG_LEVEL=FATAL CARGO_PROFILE=release CARGO_PROFILE_FLAGS=--release  nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --command bash  -c "just bridge native build.setup.eth-local.celestia-local.bridge.bridge-indexer --keep-tui"
```

**Pull request merged**
