### PR TITLE
Devaraj Framework Compatibility

### PR DESCRIPTION
**Pull request by l-monninger**
# Summary
- **RFCs**: $\emptyset$.
- **Categories**: `networks`

Changes for compatibility with Devaraj. 

# Changelog

# Testing

# Outstanding issues

### CODE REVIEW

**Comment by l-monninger** [comment]
```
celestia-light-node               | Starting Celestia light-node services.
celestia-light-node-synced        | 2024-07-08T16:14:25.495864Z  INFO wait_for_celestia_light_node: Current height: 45, Synced height: 45
celestia-light-node-synced exited with code 0
m1-da-light-node                  | 2024-07-08T16:14:26.221374Z  INFO m1_da_light_node::v1::sequencer: Initializing LightNodeV1 in sequencer mode from environment.
m1-da-light-node                  | 2024-07-08T16:14:26.224875Z  INFO m1_da_light_node::v1::sequencer: Initialized pass through for LightNodeV1 in sequencer mode.
m1-da-light-node                  | 2024-07-08T16:14:26.224925Z  INFO m1_da_light_node::v1::sequencer: Memseq path: "/.movement/memseq/b2fe0e61c3c2fb2bb164/.memseq"
m1-da-light-node                  | 2024-07-08T16:14:26.417136Z  INFO m1_da_light_node::v1::sequencer: Initialized Memseq with Move Rocks for LightNodeV1 in sequencer mode.
m1-da-light-node                  | 2024-07-08T16:14:26.417173Z  INFO m1_da_light_node: LightNodeV1 { pass_through: LightNodeV1 { celestia_namespace: Namespace(NamespaceId([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 46, 79, 45, 42, 10, 184, 221, 208, 18])) } }
dependency failed to start: container m1-da-light-node is unhealthy
error: Recipe suzuka-full-node failed on line 6 with exit code 1
```

**Comment by l-monninger** [comment]
I have not been able to reproduce on Mac arm64, Linux arm64, nor Linux amd64. A few things to check and confirm:

1. What is your `docker` version?
2. What host are you on?
3. Are you including the setup compose file, i.e., `just suzuka-full-node docker-compose setup.local`? 
4. What happens when you run with `--force-recreate`?
5. What is the output of `docker info`?
6. What are the permissions of your `.movement` directory and the parent in which it is created?

**Comment by devudilip** [comment]
Now I am getting different Error.

`suzuka-full-node                  | Error: Failed to create the executor
suzuka-full-node                  | 
suzuka-full-node                  | Caused by:
suzuka-full-node                  |     0: transport error
suzuka-full-node                  |     1: error trying to connect: tcp connect error: Connection refused (os error 111)
suzuka-full-node                  |     2: tcp connect error: Connection refused (os error 111)
suzuka-full-node                  |     3: Connection refused (os error 111)
suzuka-full-node                  | 
m1-da-light-node                  | 2024-07-09T15:25:35.155651Z  INFO m1_da_light_node::v1::sequencer: Initialized Memseq with Move Rocks for LightNodeV1 in sequencer mode.
m1-da-light-node                  | 2024-07-09T15:25:35.155699Z  INFO m1_da_light_node: LightNodeV1 { pass_through: LightNodeV1 { celestia_namespace: Namespace(NamespaceId([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 251, 141, 110, 44, 247, 123, 98, 33, 72])) } }
m1-da-light-node                  | 2024-07-09T15:25:35.155859Z  INFO m1_da_light_node::v1: Running server and background tasks.
m1-da-light-node                  | 2024-07-09T15:25:35.156950Z  INFO m1_da_light_node::v1: Server listening on: 0.0.0.0:30730
suzuka-full-node exited with code 1
wait-for-suzuka-full-node         | Waiting for suzuka-full-node to be ready...
wait-for-suzuka-full-node         | suzuka-full-node is ready`

Faucer service stops because suzuka is not running.

`Caused by:
suzuka-faucet-service             |     0: Failed to build MintFunder
suzuka-faucet-service             |     1: Failed to make MintFunder use delegated account
suzuka-faucet-service             |     2: Failed to create new account
suzuka-faucet-service             |     3: Error(41): funder account 0x000000000000000000000000000000000000000000000000000000000a550c18 not found: Unknown error error sending request for url (http://suzuka-full-node:30731/v1/accounts/000000000000000000000000000000000000000000000000000000000a550c18): error trying to connect: dns error: failed to lookup address information: Name or service not known: []
suzuka-faucet-service             | 
suzuka-faucet-service exited with code 1
`


Git branch I am running
`devaraj/framework-compatibility`

OS and host
`Mac OS 13.5 and Localhost`

Docker Version
`Docker version 24.0.5, build ced0996`

command I am running
`just suzuka-full-node docker-compose setup.local`

**Comment by l-monninger** [comment]
> OS and host
> Mac OS 13.5 and Localhost

Sorry, I meant information about your host system. OS and architecture. Thanks!

**Comment by devudilip** [comment]
@l-monninger 
command just suzuka-full-node docker-compose setup.local doesnt work anymore. 
movement/docker/compose/suzuka-full-node/docker-compose.setup.yml: no such file or directory

**Comment by mcmillennick** [comment]
@devudilip try `just suzuka-full-node docker-compose setup-local` looks like the docker-compose file for the setup might have been changed

**Comment by l-monninger** [comment]
@mcmillennick @devudilip Yes, quite a lot has changed since this thread was active.

It's actually...

```shell
just suzuka-full-node docker-compose setup-local.celestia-local
```

For cases where you are expecting a lot of faucet traffic, you may also want the `faucet-replicas` overlay.

```shell
just suzuka-full-node docker-compose setup-local.celestia-local.faucet-replicas
```

**Comment by devudilip** [comment]
@l-monninger @mcmillennick 
facing the below issues now

> Attaching to celestia-light-node, celestia-light-node-synced, m1-da-light-node, m1-da-light-node-celestia-appd, m1-da-light-node-celestia-bridge, setup, suzuka-faucet-service, suzuka-faucet-service-replica-1, suzuka-faucet-service-replica-2, suzuka-faucet-service-replica-3, suzuka-faucet-service-replica-4, suzuka-faucet-service-replica-5, suzuka-faucet-service-replica-6, suzuka-faucet-service-replica-7, suzuka-full-node
> setup                             | 2024-08-28T13:31:19.097376Z  INFO m1_da_light_node_setup::local: M1 DA Light Node is already initialized.
> setup                             | 2024-08-28T13:31:19.097433Z  INFO suzuka_full_node_setup: SuzukaFullNodeSetup: Finished setup with config: Config {
> setup                             |     execution_config: MaptosConfig {
> setup                             |         maptos_config: Config {
> setup                             |             chain: Config {
> setup                             |                 maptos_chain_id: 27,
> setup                             |                 maptos_rest_listen_hostname: "0.0.0.0",
> setup                             |                 maptos_rest_listen_port: 30731,
> setup                             |                 maptos_private_key: <elided secret for Ed25519PrivateKey>,
> setup                             |                 maptos_db_path: Some(
> setup                             |                     "/.movement/maptos/27/.maptos",
> setup                             |                 ),
> setup                             |             },
> setup                             |             client: Config {
> setup                             |                 maptos_rest_connection_hostname: "suzuka-full-node",
> setup                             |                 maptos_rest_connection_port: 30731,
> setup                             |                 maptos_faucet_rest_connection_hostname: "suzuka-faucet-service",
> setup                             |                 maptos_faucet_rest_connection_port: 30732,
> setup                             |             },
> setup                             |             faucet: Config {
> setup                             |                 maptos_rest_connection_hostname: "suzuka-full-node",
> setup                             |                 maptos_rest_connection_port: 30731,
> setup                             |                 maptos_faucet_rest_listen_hostname: "0.0.0.0",
> setup                             |                 maptos_faucet_rest_listen_port: 30732,
> setup                             |             },
> setup                             |             fin: Config {
> setup                             |                 fin_rest_listen_hostname: "0.0.0.0",
> setup                             |                 fin_rest_listen_port: 30733,
> setup                             |             },
> setup                             |         },
> setup                             |     },
> setup                             |     m1_da_light_node: M1DaLightNodeConfig {
> setup                             |         m1_da_light_node_config: Local(
> setup                             |             Config {
> setup                             |                 appd: Config {
> setup                             |                     celestia_rpc_listen_hostname: "0.0.0.0",
> setup                             |                     celestia_rpc_listen_port: 26657,
> setup                             |                     celestia_websocket_connection_hostname: "m1-da-light-node-celestia-bridge",
> setup                             |                     celestia_websocket_connection_port: 26658,
> setup                             |                     celestia_auth_token: Some(
> setup                             |                         "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiLCJhZG1pbiJdfQ.dcb-iNaW5BVC7n1S6Bgi2rRyQZGN1_D8Px-gXfcf_Yk",
> setup                             |                     ),
> setup                             |                     celestia_chain_id: "0cb2655ae3d8f50cfc75",
> setup                             |                     celestia_namespace: Namespace(
> setup                             |                         NamespaceId(
> setup                             |                             [
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 0,
> setup                             |                                 147,
> setup                             |                                 134,
> setup                             |                                 138,
> setup                             |                                 71,
> setup                             |                                 205,
> setup                             |                                 162,
> setup                             |                                 179,
> setup                             |                                 58,
> setup                             |                                 236,
> setup                             |                                 186,
> setup                             |                             ],
> setup                             |                         ),
> setup                             |                     ),
> setup                             |                     celestia_path: Some(
> setup                             |                         "/.movement/celestia/0cb2655ae3d8f50cfc75/.celestia-app",
> setup                             |                     ),
> setup                             |                     celestia_validator_address: Some(
> setup                             |                         "celestia1t97m584alufwn7k5lcmf32jvv7qhxseeqzkjfy",
> setup                             |                     ),
> setup                             |                     celestia_appd_use_replace_args: false,
> setup                             |                     celestia_appd_replace_args: [],
> setup                             |                 },
> setup                             |                 bridge: Config {
> setup                             |                     celestia_rpc_connection_hostname: "m1-da-light-node-celestia-appd",
> setup                             |                     celestia_rpc_connection_port: 26657,
> setup                             |                     celestia_websocket_listen_hostname: "0.0.0.0",
> setup                             |                     celestia_websocket_listen_port: 26658,
> setup                             |                     celestia_bridge_path: Some(
> setup                             |                         "/.movement/celestia/0cb2655ae3d8f50cfc75/.celestia-node",
> setup                             |                     ),
> setup                             |                     celestia_bridge_use_replace_args: false,
> setup                             |                     celestia_bridge_replace_args: [],
> setup                             |                 },
> setup                             |                 m1_da_light_node: Config {
> setup                             |                     celestia_rpc_connection_hostname: "m1-da-light-node-celestia-appd",
> setup                             |                     celestia_rpc_connection_port: 26657,
> setup                             |                     celestia_websocket_connection_hostname: "m1-da-light-node-celestia-bridge",
> setup                             |                     celestia_websocket_connection_port: 26658,
> setup                             |                     m1_da_light_node_listen_hostname: "0.0.0.0",
> setup                             |                     m1_da_light_node_listen_port: 30730,
> setup                             |                     m1_da_light_node_connection_hostname: "m1-da-light-node",
> setup                             |                     m1_da_light_node_connection_port: 30730,
> setup                             |                 },
> setup                             |                 celestia_force_new_chain: true,
> setup                             |                 memseq: Config {
> setup                             |                     sequencer_chain_id: Some(
> setup                             |                         "0cb2655ae3d8f50cfc75",
> setup                             |                     ),
> setup                             |                     sequencer_database_path: Some(
> setup                             |                         "/.movement/memseq/0cb2655ae3d8f50cfc75/.memseq",
> setup                             |                     ),
> setup                             |                 },
> setup                             |                 m1_da_light_node_is_initial: false,
> setup                             |             },
> setup                             |         ),
> setup                             |     },
> setup                             |     mcr: Config {
> setup                             |         rpc_url: Some(
> setup                             |             "http://localhost:8545",
> setup                             |         ),
> setup                             |         ws_url: Some(
> setup                             |             "ws://localhost:8546",
> setup                             |         ),
> setup                             |         signer_private_key: Some(
> setup                             |             "0xed02f3d0a13a9ca9c2dd00ad77d58a366c652cfb29a0308b4922a2a66d0a4d49",
> setup                             |         ),
> setup                             |         mcr_contract_address: "0xBf7c7AE15E23B2E19C7a1e3c36e245A71500e181",
> setup                             |         gas_limit: 10000000000,
> setup                             |         num_tx_send_retries: 10,
> setup                             |     },
> setup                             | }
> setup exited with code 0
> dependency failed to start: container setup exited (0)
> error: Recipe `suzuka-full-node` failed on line 6 with exit code 1

**Comment by l-monninger** [comment]
@devudilip Are you running this locally? This seems most similar to issues that occur when the host has not actually allocated enough resources for the full node to run and pass checks.

**Comment by l-monninger** [comment]
The easiest public way to validate these things is to compare your environment and machine specs with those used in our CI.

**Comment by devudilip** [comment]
@l-monninger 

I am using the Ubuntu VM, but still facing an issue.

`814400s"},"redelegations":[],"unbonding_delegations":[],"validators":[]},"transfer":{"denom_traces":[],"params":{"receive_enabled":true,"send_enabled":true},"port_id":"transfer"},"vesting":{}},"chain_id":"d350e0fd55297d81638d","gentxs_dir":"","moniker":"d350e0fd55297d81638d","node_id":"5cdf64e0b1389df91e88596fc98231ec1b744c4e"}
setup                             | 2024-09-12T14:15:33.379253Z  INFO m1_da_light_node_setup::local: Adding the validator key.
setup                             | Running command: celestia-appd keys add validator --keyring-backend=test --home /.movement/celestia/d350e0fd55297d81638d/.celestia-app
setup                             | 
setup                             | - address: celestia1yuqj4sd4wvh8y28pe2xcrz20flwmcu6u8urdew
setup                             |   name: validator
setup                             | 
setup                             | **Important** write this mnemonic phrase in a safe place.
setup                             | It is the only way to recover your account if you ever forget your password.
setup                             | 
setup                             |   pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A4MUPbOAvK20O+EqL2XkB6mOlBw4DRBJ9sAbnrtvSlcw"}'
setup                             |   type: local
setup                             | 
setup                             | hover abuse dove useless shy skill popular noodle unusual unaware jewel antenna belt jewel uphold vault over diary chunk inform mind behind exotic example
setup                             | 
setup                             | 2024-09-12T14:15:33.451574Z  INFO m1_da_light_node_setup::local: Getting the validator address.
setup                             | Running command: celestia-appd keys show validator -a --keyring-backend=test --home /.movement/celestia/d350e0fd55297d81638d/.celestia-app
setup                             | celestia1yuqj4sd4wvh8y28pe2xcrz20flwmcu6u8urdew
setup                             | 2024-09-12T14:15:33.529571Z  INFO m1_da_light_node_setup::local: Adding the genesis account.
setup                             | Running command: celestia-appd add-genesis-account celestia1yuqj4sd4wvh8y28pe2xcrz20flwmcu6u8urdew 1000000000000000utia --home /.movement/celestia/d350e0fd55297d81638d/.celestia-app
setup                             | 2024-09-12T14:15:33.578583Z  INFO m1_da_light_node_setup::local: Creating the genesis transaction.
setup                             | Running command: celestia-appd gentx validator 5000000000utia --keyring-backend=test --chain-id d350e0fd55297d81638d --home /.movement/celestia/d350e0fd55297d81638d/.celestia-app
setup                             | Genesis transaction written to "/.movement/celestia/d350e0fd55297d81638d/.celestia-app/config/gentx/gentx-5cdf64e0b1389df91e88596fc98231ec1b744c4e.json"
setup                             | 2024-09-12T14:15:33.691303Z  INFO m1_da_light_node_setup::local: Collecting the genesis transactions.
setup                             | Running command: celestia-appd collect-gentxs --home /.movement/celestia/d350e0fd55297d81638d/.celestia-app
setup                             | {"app_message":{"auth":{"accounts":[{"@type":"/cosmos.auth.v1beta1.BaseAccount","account_number":"0","address":"celestia1yuqj4sd4wvh8y28pe2xcrz20flwmcu6u8urdew","pub_key":null,"sequence":"0"}],"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","tx_size_cost_per_byte":"10"}},"authz":{"authorization":[]},"bank":{"balances":[{"address":"celestia1yuqj4sd4wvh8y28pe2xcrz20flwmcu6u8urdew","coins":[{"amount":"1000000000000000","denom":"utia"}]}],"denom_metadata":[{"base":"utia","denom_units":[{"aliases":["microtia"],"denom":"utia","exponent":0},{"aliases":[],"denom":"TIA","exponent":6}],"description":"The native token of the Celestia network.","display":"TIA","name":"TIA","symbol":"TIA","uri":"","uri_hash":""}],"params":{"default_send_enabled":true,"send_enabled":[]},"supply":[{"amount":"1000000000000000","denom":"utia"}]},"blob":{"params":{"gas_per_blob_byte":8,"gov_max_square_size":"64"}},"capability":{"index":"1","owners":[]},"crisis":{"constant_fee":{"amount":"1000","denom":"utia"}},"distribution":{"delegator_starting_infos":[],"delegator_withdraw_infos":[],"fee_pool":{"community_pool":[]},"outstanding_rewards":[],"params":{"base_proposer_reward":"0.000000000000000000","bonus_proposer_reward":"0.000000000000000000","community_tax":"0.020000000000000000","withdraw_addr_enabled":true},"previous_proposer":"","validator_accumulated_commissions":[],"validator_current_rewards":[],"validator_historical_rewards":[],"validator_slash_events":[]},"evidence":{"evidence":[]},"feegrant":{"allowances":[]},"genutil":{"gen_txs":[{"auth_info":{"fee":{"amount":[],"gas_limit":"210000","granter":"","payer":""},"signer_infos":[{"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"public_key":{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A4MUPbOAvK20O+EqL2XkB6mOlBw4DRBJ9sAbnrtvSlcw"},"sequence":"0"}],"tip":null},"body":{"extension_options":[],"memo":"5cdf64e0b1389df91e88596fc98231ec1b744c4e@172.18.0.2:26656","messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","commission":{"max_change_rate":"0.010000000000000000","max_rate":"0.200000000000000000","rate":"0.100000000000000000"},"delegator_address":"celestia1yuqj4sd4wvh8y28pe2xcrz20flwmcu6u8urdew","description":{"details":"","identity":"","moniker":"d350e0fd55297d81638d","security_contact":"","website":""},"min_self_delegation":"1","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"KiudWapCLie7Rv2z4YtvizFsLq95ytsSy/8IiRjL0nE="},"validator_address":"celestiavaloper1yuqj4sd4wvh8y28pe2xcrz20flwmcu6uzrp50g","value":{"amount":"5000000000","denom":"utia"}}],"non_critical_extension_options":[],"timeout_height":"0"},"signatures":["WVCyBWf8OsuqwMck6P++NkpUMtAbDElWBTYttUWuHml3a+qw3Rcy4blkV32NpVKVEeEDs5H9Vn5emsqhysFg3Q=="]}]},"gov":{"deposit_params":{"max_deposit_period":"604800s","min_deposit":[{"amount":"10000000000","denom":"utia"}]},"deposits":[],"proposals":[],"starting_proposal_id":"1","tally_params":{"quorum":"0.334000000000000000","threshold":"0.500000000000000000","veto_threshold":"0.334000000000000000"},"votes":[],"voting_params":{"voting_period":"604800s"}},"ibc":{"channel_genesis":{"ack_sequences":[],"acknowledgements":[],"channels":[],"commitments":[],"next_channel_sequence":"0","receipts":[],"recv_sequences":[],"send_sequences":[]},"client_genesis":{"clients":[],"clients_consensus":[],"clients_metadata":[],"create_localhost":false,"next_client_sequence":"0","params":{"allowed_clients":["06-solomachine","07-tendermint"]}},"connection_genesis":{"client_connection_paths":[],"connections":[],"next_connection_sequence":"0","params":{"max_expected_time_per_block":"75000000000"}}},"mint":{"bond_denom":"utia"},"params":null,"qgb":{"params":{"data_commitment_window":"400"}},"slashing":{"missed_blocks":[],"params":{"downtime_jail_duration":"60s","min_signed_per_window":"0.750000000000000000","signed_blocks_window":"5000","slash_fraction_double_sign":"0.020000000000000000","slash_fraction_downtime":"0.000000000000000000"},"signing_infos":[]},"staking":{"delegations":[],"exported":false,"last_total_power":"0","last_validator_powers":[],"params":{"bond_denom":"utia","historical_entries":10000,"max_entries":7,"max_validators":100,"min_commission_rate":"0.050000000000000000","unbonding_time":"1814400s"},"redelegations":[],"unbonding_delegations":[],"validators":[]},"transfer":{"denom_traces":[],"params":{"receive_enabled":true,"send_enabled":true},"port_id":"transfer"},"vesting":{}},"chain_id":"d350e0fd55297d81638d","gentxs_dir":"/.movement/celestia/d350e0fd55297d81638d/.celestia-app/config/gentx","moniker":"d350e0fd55297d81638d","node_id":"5cdf64e0b1389df91e88596fc98231ec1b744c4e"}
setup                             | 2024-09-12T14:15:33.773911Z  INFO m1_da_light_node_setup::local: Updating the Celestia Node config.
setup                             | Running command: sed -i.bak s#"tcp://0.0.0.0:26657"#"tcp://0.0.0.0:26657"#g /.movement/celestia/d350e0fd55297d81638d/.celestia-app/config/config.toml
setup                             | Running command: sed -i.bak s/^timeout_commit\s*=.*/timeout_commit = "2s"/g /.movement/celestia/d350e0fd55297d81638d/.celestia-app/config/config.toml
setup                             | Running command: sed -i.bak s/^timeout_propose\s*=.*/timeout_propose = "2s"/g /.movement/celestia/d350e0fd55297d81638d/.celestia-app/config/config.toml
setup                             | 2024-09-12T14:15:33.777562Z  INFO m1_da_light_node_setup::local: Copying keys from Celestia App to Celestia Node.
setup                             | 2024-09-12T14:15:33.778051Z  INFO m1_da_light_node_setup::local: Getting the auth token.
setup                             | Running command: celestia bridge auth admin --node.store /.movement/celestia/d350e0fd55297d81638d/.celestia-node
setup                             | eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiLCJhZG1pbiJdfQ.-UpkVqwfceyDW3Gd7rIxk3FsORI4BWidk2CNPAqZVtk
setup                             | 2024-09-12T14:15:33.818208Z  INFO m1_da_light_node_setup::local: Celestia setup complete.
setup                             | 2024-09-12T14:15:33.818227Z  INFO m1_da_light_node_setup::local: M1 DA Light Node setup complete.
setup                             | 2024-09-12T14:15:33.818234Z  INFO suzuka_full_node_setup: SuzukaFullNodeSetup: Finished setup with config: Config {
setup                             |     execution_config: MaptosConfig {
setup                             |         maptos_config: Config {
setup                             |             chain: Config {
setup                             |                 maptos_chain_id: 27,
setup                             |                 maptos_rest_listen_hostname: "0.0.0.0",
setup                             |                 maptos_rest_listen_port: 30731,
setup                             |                 maptos_private_key: <elided secret for Ed25519PrivateKey>,
setup                             |                 maptos_db_path: Some(
setup                             |                     "/.movement/maptos/27/.maptos",
setup                             |                 ),
setup                             |             },
setup                             |             client: Config {
setup                             |                 maptos_rest_connection_hostname: "suzuka-full-node",
setup                             |                 maptos_rest_connection_port: 30731,
setup                             |                 maptos_faucet_rest_connection_hostname: "suzuka-faucet-service",
setup                             |                 maptos_faucet_rest_connection_port: 30732,
setup                             |             },
setup                             |             faucet: Config {
setup                             |                 maptos_rest_connection_hostname: "suzuka-full-node",
setup                             |                 maptos_rest_connection_port: 30731,
setup                             |                 maptos_faucet_rest_listen_hostname: "0.0.0.0",
setup                             |                 maptos_faucet_rest_listen_port: 30732,
setup                             |             },
setup                             |             fin: Config {
setup                             |                 fin_rest_listen_hostname: "0.0.0.0",
setup                             |                 fin_rest_listen_port: 30733,
setup                             |             },
setup                             |         },
setup                             |     },
setup                             |     m1_da_light_node: M1DaLightNodeConfig {
setup                             |         m1_da_light_node_config: Local(
setup                             |             Config {
setup                             |                 appd: Config {
setup                             |                     celestia_rpc_listen_hostname: "0.0.0.0",
setup                             |                     celestia_rpc_listen_port: 26657,
setup                             |                     celestia_websocket_connection_hostname: "m1-da-light-node-celestia-bridge",
setup                             |                     celestia_websocket_connection_port: 26658,
setup                             |                     celestia_auth_token: Some(
setup                             |                         "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiLCJhZG1pbiJdfQ.-UpkVqwfceyDW3Gd7rIxk3FsORI4BWidk2CNPAqZVtk",
setup                             |                     ),
setup                             |                     celestia_chain_id: "d350e0fd55297d81638d",
setup                             |                     celestia_namespace: Namespace(
setup                             |                         NamespaceId(
setup                             |                             [
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 0,
setup                             |                                 104,
setup                             |                                 151,
setup                             |                                 148,
setup                             |                                 81,
setup                             |                                 84,
setup                             |                                 164,
setup                             |                                 15,
setup                             |                                 204,
setup                             |                                 71,
setup                             |                                 75,
setup                             |                             ],
setup                             |                         ),
setup                             |                     ),
setup                             |                     celestia_path: Some(
setup                             |                         "/.movement/celestia/d350e0fd55297d81638d/.celestia-app",
setup                             |                     ),
setup                             |                     celestia_validator_address: Some(
setup                             |                         "celestia1yuqj4sd4wvh8y28pe2xcrz20flwmcu6u8urdew",
setup                             |                     ),
setup                             |                     celestia_appd_use_replace_args: false,
setup                             |                     celestia_appd_replace_args: [],
setup                             |                 },
setup                             |                 bridge: Config {
setup                             |                     celestia_rpc_connection_hostname: "m1-da-light-node-celestia-appd",
setup                             |                     celestia_rpc_connection_port: 26657,
setup                             |                     celestia_websocket_listen_hostname: "0.0.0.0",
setup                             |                     celestia_websocket_listen_port: 26658,
setup                             |                     celestia_bridge_path: Some(
setup                             |                         "/.movement/celestia/d350e0fd55297d81638d/.celestia-node",
setup                             |                     ),
setup                             |                     celestia_bridge_use_replace_args: false,
setup                             |                     celestia_bridge_replace_args: [],
setup                             |                 },
setup                             |                 m1_da_light_node: Config {
setup                             |                     celestia_rpc_connection_hostname: "m1-da-light-node-celestia-appd",
setup                             |                     celestia_rpc_connection_port: 26657,
setup                             |                     celestia_websocket_connection_hostname: "m1-da-light-node-celestia-bridge",
setup                             |                     celestia_websocket_connection_port: 26658,
setup                             |                     m1_da_light_node_listen_hostname: "0.0.0.0",
setup                             |                     m1_da_light_node_listen_port: 30730,
setup                             |                     m1_da_light_node_connection_hostname: "m1-da-light-node",
setup                             |                     m1_da_light_node_connection_port: 30730,
setup                             |                 },
setup                             |                 celestia_force_new_chain: true,
setup                             |                 memseq: Config {
setup                             |                     sequencer_chain_id: Some(
setup                             |                         "d350e0fd55297d81638d",
setup                             |                     ),
setup                             |                     sequencer_database_path: Some(
setup                             |                         "/.movement/memseq/d350e0fd55297d81638d/.memseq",
setup                             |                     ),
setup                             |                 },
setup                             |                 m1_da_light_node_is_initial: false,
setup                             |             },
setup                             |         ),
setup                             |     },
setup                             |     mcr: Config {
setup                             |         rpc_url: Some(
setup                             |             "http://localhost:8545",
setup                             |         ),
setup                             |         ws_url: Some(
setup                             |             "ws://localhost:8546",
setup                             |         ),
setup                             |         signer_private_key: Some(
setup                             |             "0x0d35ee4e3ae7f07fc2234087e6993873b024aa940ae68e5395823fe77a1b6250",
setup                             |         ),
setup                             |         mcr_contract_address: "0xBf7c7AE15E23B2E19C7a1e3c36e245A71500e181",
setup                             |         gas_limit: 10000000000,
setup                             |         num_tx_send_retries: 10,
setup                             |     },
setup                             | }`

**Comment by devudilip** [comment]
@l-monninger 
we can run the Docker  now http://15.235.41.80:8090/

Docker ps looks like this:
`3c72cc3e0c4b   ghcr.io/movementlabsxyz/suzuka-faucet-service:93ff017680d5c7ca30ee67bb63bee3f9c8fff6cc              "/app/suzuka-faucet-…"    36 minutes ago   Up 22 minutes (healthy)   0.0.0.0:30732->30732/tcp, :::30732->30732/tcp                                                  suzuka-faucet-service
`
`24de06378617   ghcr.io/movementlabsxyz/suzuka-full-node:93ff017680d5c7ca30ee67bb63bee3f9c8fff6cc                   "/app/suzuka-full-no…"    36 minutes ago   Up 22 minutes (healthy)   0.0.0.0:30731->30731/tcp, :::30731->30731/tcp, 0.0.0.0:30734->30734/tcp, :::30734->30734/tcp   suzuka-full-node`

`6f92c04f76a2   ghcr.io/movementlabsxyz/m1-da-light-node:93ff017680d5c7ca30ee67bb63bee3f9c8fff6cc                   "/app/m1-da-light-no…"    36 minutes ago   Up 22 minutes (healthy)   0.0.0.0:30730->30730/tcp, :::30730->30730/tcp                                                  m1-da-light-node`

`dd659e1f355f   busybox                                                                                             "sh -c 'echo \"Starti…"   36 minutes ago   Up 22 minutes (healthy)                                                                                                  celestia-light-node`

`0f4935308250   ghcr.io/movementlabsxyz/m1-da-light-node-celestia-bridge:93ff017680d5c7ca30ee67bb63bee3f9c8fff6cc   "/app/m1-da-light-no…"    36 minutes ago   Up 22 minutes (healthy)   0.0.0.0:26658->26658/tcp, :::26658->26658/tcp                                                  m1-da-light-node-celestia-bridge`

`7573c5d23b4a   ghcr.io/movementlabsxyz/m1-da-light-node-celestia-appd:93ff017680d5c7ca30ee67bb63bee3f9c8fff6cc     "/app/m1-da-light-no…"    36 minutes ago   Up 22 minutes (healthy)   0.0.0.0:9090->9090/tcp, :::9090->9090/tcp, 0.0.0.0:26657->26657/tcp, :::26657->26657/tcp       m1-da-light-node-celestia-appd`

`d9cc2985cabf   ghcr.io/movementlabsxyz/suzuka-full-node-setup:93ff017680d5c7ca30ee67bb63bee3f9c8fff6cc             "/app/suzuka-full-no…"    36 minutes ago   Up 22 minutes (healthy)   0.0.0.0:8090->8090/tcp, :::8090->8090/tcp                                                      setup`

**Pull request closed without merging**
