### PR TITLE
fix: add cors.

### PR DESCRIPTION
**Pull request by l-monninger**
# Summary
- **Status**: `draft` 
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.

WIP. I believe this has fallen out a few times. It is needed for local testing with the browser OFC. 

# Changelog

# Testing

# Outstanding issues

### CODE REVIEW

**Comment by 0xPrimata** [comment]
@l-monninger right below line 366 it requires `.allow_credentials(true);`
explorer is able to read it if its added 🙏🏽 
image

**Review by 0xPrimata — APPROVED** [review]

**Comment by l-monninger** [comment]
@0xPrimata there are a few more policies they set in the upstream. I will check which apply and add as needed before we merge here.

**Comment by l-monninger** [comment]
This is the note from upstream: https://github.com/movementlabsxyz/aptos-core/blob/ea91067b81f9673547417bff9c70d5a2fe1b0e7b/api/src/runtime.rs#L209

**Comment by l-monninger** [comment]
@0xPrimata  If the above passes I will unmark as draft, then we can drop the other reviewers and merge.

**Comment by 0xPrimata** [comment]
`.allow_methods(vec![Method::GET, Method::POST]);` isn't really necessary since it's reducing the scope of possible methods. All methods are allowed by default. Maybe good to add though.
https://docs.rs/poem/latest/poem/middleware/struct.Cors.html#method.allow_method

**Comment by l-monninger** [comment]
@0xPrimata It's just to match the upstream.

**Pull request merged**
