### PR TITLE
Trusted Native Bridge

### PR DESCRIPTION
**Pull request by Primata**
# Summary
- **RFCs**: [Link to RFC](#./link/to/rfc), [Link to RFC](#./link/to/rfc), or $\emptyset$.
- **Categories**: any of `protocol-units`, `networks`, `scripts`, `util`, `cicd`, or `misc`.

Reduces the amount of calls on Solidity Bridge Contracts to initiate and complete
Combines contracts
Removes user secret sharing requirement

# Changelog

* Reduces the amount of calls on Solidity Bridge Contracts to initiate and complete
* Combines initiator and counterparty contracts
* Removes user secret sharing requirement
* Removes timelock
* Proposes an additional maintainer multigi that can perform RELAYER_ROLE tasks.
* Bridge can only be completed by relayers

# Testing

fuzz test on initiateBridge
fuzz test on completeBridge

# Outstanding issues

Move side

### CODE REVIEW

**Comment by 0xmovses** [comment]
conflicts 

I would remove all the renaming completely from this PR as this PR just should focus on the contracts not renaming. Merge in main and accept all the changes from main. 

Renaming in a seperate PR, that should resolve them all <3

**Comment by Primata** [comment]
> conflicts
> 
> I would remove all the renaming completely from this PR as this PR just should focus on the contracts not renaming. Merge in main and accept all the changes from main.
> 
> Renaming in a seperate PR, that should resolve them all.

bridge contract is already merged into a single one, can't keep the old names

**Comment by 0xmovses** [comment]
@Primata Ok you can resolve the conflicts for the contracts then by keeping your changes, but for the rest you can accept changes from main. Anyway it's up to you how you want to resolve them, was just a suggestion as to how I'd approach it.

**Comment by 0xmovses** [comment]
tests are passing, contracts look good to me

**Review by 0xmovses — APPROVED** [review]

**Pull request merged**
